dist: focal
os: linux
language: python
branches:
  only:
    - master
jobs:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py38
cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - wget https://github.com/jadbin/guniflask/archive/master.zip
  - unzip master.zip
install:
  - pip install tox coveralls
script:
  - tox --recreate
after_success:
  - coveralls
