FROM python:3.9

ENV TZ={{timezone}} \
  DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
  && echo ${TZ} > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata \
  && rm -rf /var/lib/apt/lists/*

ADD ./requirements /opt/requirements
RUN pip install -r /opt/requirements/app.txt \
  && rm -rf ~/.cache

ADD ./ /opt/{{project_name}}
WORKDIR /opt/{{project_name}}
RUN chmod +x bin/manage

ENTRYPOINT ["bin/manage", "start", "--daemon-off"]
