FROM python:3.7

ADD ./ /opt/{{project_name}}
WORKDIR /opt/{{project_name}}

ENV TZ={{timezone}} \
  DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
  && echo ${TZ} > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata \
  && rm -rf /var/lib/apt/lists/*

RUN chmod +x bin/manage \
  && pip install -r requirements/app.txt \
  && rm -rf ~/.cache

ENTRYPOINT ["bin/manage", "start", "--daemon-off"]
